name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build binary
        run: go build -o app-linux-amd64

      - name: Run tests
        run: go test -v ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-app-binary
          path: app-linux-amd64

      - name: Upload binary with scp (manual)
        run: |
          echo "${{ secrets.VPS_KEY }}" | base64 -d > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key app-linux-amd64 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/order-management-api/
