name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build binary
      run: go build -o app-linux-amd64

    - name: Run tests
      run: go test -v ./...

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-app-binary
        path: app-linux-amd64

    - name: Upload binary to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        source: "app-linux-amd64"
        target: "/var/www/order-management-api"
