name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build binary
        run: go build -o app-linux-amd64

      - name: Run tests
        run: go test -v ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-app-binary
          path: app-linux-amd64

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Ensure remote directory exists (as root)
        run: |
          echo "🔧 Memastikan direktori target tersedia di VPS..."
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} \
            root@${{ secrets.VPS_HOST }} \
            "mkdir -p /var/www/order-management-api && chmod 755 /var/www/order-management-api"

      - name: Upload binary to /root (to avoid overwrite conflict)
        run: |
          echo "📦 Upload binary sementara ke /root..."
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
            scp -o StrictHostKeyChecking=no -P ${{ secrets.VPS_PORT }} \
            app-linux-amd64 \
            root@${{ secrets.VPS_HOST }}:/root/app-linux-amd64

      - name: Replace binary and restart goweb service
        run: |
          echo "🔁 Mengganti binary dan restart service goweb..."
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} \
            root@${{ secrets.VPS_HOST }} << 'EOF'
              echo "⛔ Menghentikan service goweb..."
              systemctl stop goweb

              echo "📂 Memindahkan binary baru ke folder target..."
              mv /root/app-linux-amd64 /var/www/order-management-api/app-linux-amd64
              chmod +x /var/www/order-management-api/app-linux-amd64

              echo "🚀 Menyalakan kembali service goweb..."
              systemctl start goweb
              systemctl status goweb --no-pager || true
          EOF

      - name: List files in target directory (debugging)
        run: |
          echo "📁 Menampilkan isi folder target (debug)..."
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} \
            root@${{ secrets.VPS_HOST }} \
            "ls -lah /var/www/order-management-api"
